apiVersion: v1
kind: Service
metadata:
  name: java-webapp
  namespace: java-webapp
spec:
  type: NodePort
  selector:
    app: java-webapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31001
