apiVersion: apps/v1
kind: Deployment
metadata:
  name: Java-Webapp
  namespace: grade-demo
  labels:
    app: Java-Webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Java-Webapp
  template:
    metadata:
      labels:
        app: Java-Webapp
    spec:
      containers:
      - name: Java-Webapp
        image: abhishekf5/ultimate-cicd:22 # rslim087/kubernetes-course-grade-submission-api:stateless
        ports:
          - containerPort: 3000